name: Build For Release, Package Docker Image, & Publish To Registry
on:
  workflow_run: 
    workflows: ["Restore, Build, & Test"]
    types: [completed]
    branches: [main]

jobs:
  build-package-publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Setup .NET
#        uses: actions/setup-dotnet@v4
#        with:
#          dotnet-version: '10.0.x'

#      - name: Restore dependencies
#        run: dotnet restore

#      - name: Build solution
#        run: dotnet build --no-restore --configuration Release

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag maaldocom-web:latest
