name: Release to Development

on:
  workflow_run:
    workflows: ["Build For Release, Package Docker Image, & Publish To Registry"]
    types: [completed]
    branches: [main]

jobs:
  release-to-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    runs-on: ubuntu-latest

    steps:
      - name: Say hi
        run: echo "hi..."

      