name: Restore, Build, & Test
on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  restore-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Setup .NET
#        uses: actions/setup-dotnet@v4
#        with:
#          dotnet-version: '10.0.x'

#      - name: Restore dependencies
#        run: dotnet restore

#      - name: Build solution
#        run: dotnet build --no-restore --configuration Release
      
#      - name: Run tests
#        run: dotnet test --no-restore --logger:"junit;LogFilePath=${{ github.workspace }}/results/test-results.xml"

#      - name: Create test summary
#        uses: test-summary/action@v2.4
#        with:
#          paths: ${{ github.workspace }}/results/*.xml
#          output: ${{ github.workspace }}/results/summary.md
#          show: "all"
#        if: always()

#      - name: Add Test Results To Job Summary
#        run: |
#          echo "TEST RESULTS:" >> $GITHUB_STEP_SUMMARY
#          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
#          cat "${{ github.workspace }}/results/summary.md" >> $GITHUB_STEP_SUMMARY
#        if: always()